### ISSUE TITLE
Duplicate reference in db dump

### ISSUE THREAD

**Issue by skywalkerdude** [ReganRyanNZ/songbase#21]
In the [app data api](https://songbase.life/api/v1/app_data), one song reference is repeated twice:

```
{"id":645,"song_id":789,"book_id":2,"index":"881"},
{"id":1616,"song_id":789,"book_id":2,"index":"881"}
```

I believe this shouldn't be duplicated, right?

**Comment by ReganRyanNZ** [comment]
Hey, sorry I don't check this very often, a lot of duplicates and typos have been found, some still surface (not so often now)

Please send any you find to songbase.brothers@gmail.com
