### ISSUE TITLE
Offline usage broken

### ISSUE THREAD

**Issue by jemerald** [ReganRyanNZ/songbase#39]
Uncaught exception when calling `/api/v1/languages` API

![image](https://user-images.githubusercontent.com/9168432/205574133-f014e67e-1afc-4d4b-ba34-c6c9c28af430.png)

This happens when the app is opened while the device is offline, causing the song list not being displayed

**Comment by ReganRyanNZ** [comment]
👀  Sorry Jackie just saw this, we've migrated to api v2 now, and changed so much that I think this error is still applicable (unless you can still reproduce?)
