### ISSUE TITLE
Missing chord

### ISSUE THREAD

**Issue by Ninja666-rgb** [ReganRyanNZ/songbase#57]
There are many missing chords which you can find if you use ctr-f on the api and type '[]'. 
<img width="503" alt="image" src="https://github.com/ReganRyanNZ/songbase/assets/80719864/d42dda5f-97ac-4a54-ad61-191c596d8a6f">
<img width="271" alt="image" src="https://github.com/ReganRyanNZ/songbase/assets/80719864/b24e31ed-a56a-4bb5-8fbb-02147f19732e">

**Comment by ReganRyanNZ** [comment]
This is not a bug, but a feature™

Empty chords provide the extra spacing to the lyrics, so some people put them in on lines with no chords, if the entire stanza has chords, so each lyric line is always evenly spaced apart.

It does look a little weird, but functions ok
